site:
  title: Documentation
  start_page: home::index.adoc
  url: http:localhost:3000
  keys:
    google_analytics: 'GTM-MQ59XD6'
    docsearch_id: 'QK2EAH8GB0'
    docsearch_api: 'ef7bd9485eafbd75d6e8425949eda1f5'
    docsearch_index: 'prod_hazelcast_docs'
content:
  sources: 
  - url: .
    start_path: home
    branches: HEAD
  - url: ../caching-springboot-jcache
    branches: HEAD
  - url: .
    start_path: tutorials
    branches: HEAD
ui: 
  bundle:
    url: ../hazelcast-docs-ui/build/ui-bundle.zip
    snapshot: true
runtime:
  log:
    level: debug
antora:
  extensions:
    - require: '@djencks/antora-aggregate-collector'
      trace: true
      componentversions:
        - name: management-center
          version: '5.1-snapshot'
          mappings:
            - module: integrate
              family: attachment
              origin:
                url:
                  include:
                    - '**/hazelcast/management-center'
                branch:
                  includes:
                    - 'master'
        - name: management-center
            version: '5.1'
            mappings:
              - module: integrate
                family: attachment
                origin:
                  url:
                    include:
                      - '**/hazelcast/management-center'
                  branch:
                    includes:
                      - '5.1'
asciidoc:
  attributes:
    page-pagination: true
    idprefix: ''
    idseparator: '-'
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    imdg-javadoc: https://docs.hazelcast.org/docs/latest-dev/javadoc
    imdg-samples: https://github.com/hazelcast/hazelcast-code-samples
    imdg-core: https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast
    imdg-docs: https://docs.hazelcast.org/docs/latest/manual/html-single/index.html
    imdg-ops-guide: https://hazelcast.com/resources/hazelcast-deployment-operations-guide/
    jet-docs: https://jet-start.sh/
    docs-archive: 'https://hazelcast.org/imdg/download/archives/'
  extensions:
    - ./lib/tabs-block.js
    - ./lib/swagger-ui-block-macro.js
