site:
  title: Documentation
  url: https:/docs.hazelcast.com
content:
  sources: 
  - url: https://github.com/hazelcast/hz-docs
    branches: [v/5.0]
    start_path: docs
antora:
  extensions:
  - '@antora/pdf-extension'
ui: 
  bundle:
    url: https://github.com/hazelcast/hazelcast-docs-ui/releases/latest/download/ui-bundle.zip #../hazelcast-docs-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    # Download images from kroki at build time (does not work for inline images)
    kroki-fetch-diagram: true
    # Inlude next and previous links on each page
    page-pagination: true
    idprefix: ''
    # Separate anchor link names by dashes
    idseparator: '-'
    # Variables used in the docs
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    # Filter out content that doesn't apply to PDF such as embedded scripts
    backend-pdf: true
  extensions:
    - ./lib/tabs-block.js
    - ./lib/swagger-ui-block-macro.js